### PR TITLE
Gp 2906

### PR DESCRIPTION
**Pull request by lheisler**
testing regression tests, will correct before assigning for review

### CODE REVIEW

**Comment by lheisler** [comment]
i seem to be able to merge without reviews....i thing some settings need to be adjusted

**Review by pruzanov — APPROVED** [review]

**Review by mlaszloffy — CHANGES_REQUESTED** [review]
Can the readme be updated and 1.0.3 tag be updated to the latest commit?

**Comment by lheisler** [comment]
latest commit has now been tagged as 1.0.4

build : https://gsici.hpc.oicr.on.ca/job/crosscheckFingerprintsCollector.vidarr/view/tags/job/1.0.4/

**Review by mlaszloffy — APPROVED** [review]

**Comment by lheisler** [comment]
Readme Updated using latest gsi-wdl-tools

**Pull request merged**
